### ISSUE TITLE
Print output before command has completed

### ISSUE THREAD

**Issue by mkals** [Renaud11232/pyduinocli#5]
During commands like upload that take some time, it would be nice to be able to show the stdout information produced by the command before the function returns - is this possible to achieve?

**Comment by Renaud11232** [comment]
Hello,

I don't think this is possible due to the way arduino-cli works. AFAIK, it only prints the output right before exiting. So I don't see any way to do this.

Do you know a board that actually makes arduino-cli progressively print text on the console ?

**Comment by mkals** [comment]
Ok, thanks for your reply! I was thinking of the output reporting progress and completion of the compilation, contact with the board and initiating flashing. For STM32 boards for example, Arduino-CLI exhibits this behaviour.
